apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dpl
annotations:
  seccomp.security.alpha.kubernetes.io/pod: "docker/default" 
  container.apparmor.security.beta.kubernetes.io/hello: localhost/k8s-apparmor-example-deny-write

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: lmnzr/simplefrontend:latest@sha256:cb5c1bddd1b5665e1867a7fa1b5fa843a47ee433bbb75d4293888b71def53229
          readinessProbe:
           httpGet:
            path: /health
            port: 80
            initialDelaySeconds: 60
          livenessProbe:
           httpGet:
            path: /health
            port: 80
          env:
            - name: BACKEND_URL
              value: "http://backend-svc:8080"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 1000
              fsGroup: 2000
              readOnlyRootFilesystem: true
             
         
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: frontend
